version: '3'
services:

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8
      --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
      --innodb-flush-log-at-trx-commit=0 --bind-address=0.0.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=lemon
    volumes:
      - ./extras/initdb.d:/docker-entrypoint-initdb.d
      - /srv/lemonade/mysql-dev:/var/lib/mysql
    networks:
      default:
        aliases: [lemonade_db, db]
    restart: on-failure
    ports:
    - 33062:3306

  redis:
    image: redis:4
    networks:
      - default
    restart: on-failure

  thorn:
    build: ./thorn
    image: eubrabigsea/thorn
    volumes:
      - ./config/thorn-config.yaml:/usr/local/thorn/conf/thorn-config.yaml
    networks:
      - default
    restart: always

  thorn_worker:
    build: ./thorn
    image: eubrabigsea/thorn
    entrypoint: 
      - "/usr/bin/dumb-init"
      - "--"
      - "/usr/local/bin/entrypoint"
      - "worker"
    volumes:
      - ./config/thorn-config.yaml:/usr/local/thorn/conf/thorn-config.yaml
    networks:
      - default
    restart: always

  limonero:
    build: ./limonero
    image: eubrabigsea/limonero
    volumes:
      - ./config/limonero-config.yaml:/usr/local/limonero/conf/limonero-config.yaml
      - /srv/lemonade/storage:/srv/storage
    networks:
      - default
    restart: always

  stand:
    build: ./stand
    image: eubrabigsea/stand
    volumes:
      - ./config/stand-config.yaml:/usr/local/stand/conf/stand-config.yaml
    networks:
      - default
    restart: always

  caipirinha:
    build: ./caipirinha
    image: eubrabigsea/caipirinha
    volumes:
      - ./config/caipirinha-config.yaml:/usr/local/caipirinha/conf/caipirinha-config.yaml
    networks:
      - default
    restart: always

  tahiti:
    build: ./tahiti
    image: eubrabigsea/tahiti
    volumes:
      - ./config/tahiti-config.yaml:/usr/local/tahiti/conf/tahiti-config.yaml
    networks:
      - default
    restart: always

  juicer:
    build: ./juicer
    image: eubrabigsea/juicer
    environment:
      - HADOOP_CONF_DIR=/usr/local/juicer/conf
    command: ["/usr/local/juicer/sbin/juicer-daemon.sh", "docker"]
    volumes:
      - ./config/juicer-config.yaml:/usr/local/juicer/conf/juicer-config.yaml
      - ./config/hdfs-site.xml:/usr/local/juicer/conf/hdfs-site.xml
      - /srv/lemonade/storage:/srv/storage
      - ./lemonade-spark-ext/target/lemonade-spark-ext-1.0-SNAPSHOT.jar:/usr/local/juicer/jars/lemonade-spark-ext-1.0-SNAPSHOT.jar
      - ./spark-fairness/target/spark-fairness_2.11-1.0.jar:/usr/local/juicer/jars/spark-fairness_2.11-1.0.jar
      - ./config/metrics.properties:/usr/local/spark/conf/metrics.properties
      - ./config/jmx_collector.yaml:/usr/local/spark/conf/jmx_collector.yaml
      - ./jars/spark-metrics_2.11-2.3-2.1.0.jar:/usr/local/spark/jars/spark-metrics_2.11-2.3-2.1.0.jar
      - ./jars/metrics-core-3.1.2.jar:/usr/local/spark/jars/metrics-core-3.2.5.jar
      - ./jars/simpleclient-0.3.0.jar:/usr/local/spark/jars/simpleclient-0.3.0.jar
      - ./jars/simpleclient_dropwizard-0.3.0.jar:/usr/local/spark/jars/simpleclient_dropwizard-0.3.0.jar
      - ./jars/simpleclient_pushgateway-0.3.0.jar:/usr/local/spark/jars/simpleclient_pushgateway-0.3.0.jar
      - ./jars/collector-0.12.0.jar:/usr/local/spark/jars/collector-0.12.0.jar
    networks:
      - default
    restart: always
    # Uncomment next lines if you are connecting to an external spark cluster
    #ports:
    #  - '37100-37399:37100-37399'

  citrus:
    build: ./citrus
    image: eubrabigsea/citrus
    ports:
      - '23456:8080'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    restart: always

#   seed:
#     build: ./seed
#     image: eubrabigsea/seed
#     volumes:
#       - ./config/seed-config.yaml:/usr/local/seed/conf/seed.yaml
#     networks:
#       - default
#     restart: always
# 
#   seed_worker:
#     build: ./seed
#     image: eubrabigsea/seed
#     entrypoint: 
#       - "/usr/bin/dumb-init"
#       - "--"
#       - "/usr/local/bin/entrypoint"
#       - "worker"
#     volumes:
#       - ./config/seed-config.yaml:/usr/local/seed/conf/seed.yaml
#     networks:
#       - default
#     restart: always

  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - 23457:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    depends_on:
      - cadvisor
    networks:
      - default

  pushgateway:
    image: prom/pushgateway:v1.4.1
    ports:
      - 23458:9091
    depends_on:
      - prometheus
    networks:
      - default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.6
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    #volumes:
      #- elasticsearch:/usr/share/elasticsearch/data
    networks:
      - default

  filebeat:
    image: elastic/filebeat:7.14.0
    volumes:
      - ./config/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 23459:3000

networks:
  default:
