scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: pushgateway
  honor_labels: true
  static_configs:
  - targets:
    - pushgateway:9091

